name: Dependabot Auto Merge

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write
  checks: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: wait-for-checks
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge Dependabot PRs for non-major updates
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
