name: Autofill PR Description

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  openai-pr-description:
    runs-on: ubuntu-22.04
    if: ${{ !startsWith(github.actor, 'dependabot') }}
    steps:
      - uses: platisd/openai-pr-description@v1.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPEN_AI_PR_DESCRIPTION_API_KEY }}
